const TEST_REQUEST = 'TEST_REQUEST';
const TEST_ERROR = 'TEST_ERROR';
const TEST_SUCCESS = 'TEST_SUCCESS';

const FETCHING = 'FETCHING';

export {
    TEST_REQUEST, 
    TEST_ERROR, 
    TEST_SUCCESS,
    FETCHING
}